# CMake generated Testfile for 
# Source directory: F:/pytorch2ncnn/ncnn/tests
# Build directory: F:/pytorch2ncnn/ncnn/build_cmakegui/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mat_pixel_affine "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_mat_pixel_affine.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mat_pixel_affine "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_mat_pixel_affine.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mat_pixel_affine "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_mat_pixel_affine.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mat_pixel_affine "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_mat_pixel_affine.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_mat_pixel_affine NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mat_pixel_rotate "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_mat_pixel_rotate.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mat_pixel_rotate "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_mat_pixel_rotate.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mat_pixel_rotate "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_mat_pixel_rotate.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mat_pixel_rotate "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_mat_pixel_rotate.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_mat_pixel_rotate NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mat_pixel_resize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_mat_pixel_resize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mat_pixel_resize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_mat_pixel_resize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mat_pixel_resize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_mat_pixel_resize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mat_pixel_resize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_mat_pixel_resize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_mat_pixel_resize NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mat_pixel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_mat_pixel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mat_pixel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_mat_pixel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mat_pixel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_mat_pixel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mat_pixel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_mat_pixel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_mat_pixel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_squeezenet "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_squeezenet.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_squeezenet "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_squeezenet.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_squeezenet "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_squeezenet.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_squeezenet "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_squeezenet.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_squeezenet NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_cpu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_cpu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_cpu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_cpu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_cpu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_cpu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_cpu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_cpu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_cpu NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_absval "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_absval.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_absval "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_absval.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_absval "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_absval.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_absval "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_absval.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_absval NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_batchnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_batchnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_batchnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_batchnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_batchnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_batchnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_batchnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_batchnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_batchnorm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_binaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_binaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_binaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_binaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_binaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_binaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_binaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_binaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_binaryop NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_cast "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_cast.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_cast "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_cast.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_cast "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_cast.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_cast "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_cast.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_clip "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_clip.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_clip "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_clip.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_clip "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_clip.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_clip "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_clip.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_clip NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_concat "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_concat.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_concat "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_concat.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_concat "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_concat.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_concat "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_concat.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_concat NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_convolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_convolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_convolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_convolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_convolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_convolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_convolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_convolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_convolution NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_convolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_convolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_convolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_convolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_convolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_convolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_convolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_convolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_convolutiondepthwise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_crop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_crop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_crop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_crop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_crop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_crop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_crop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_crop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_crop NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_deconvolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_deconvolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_deconvolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_deconvolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_deconvolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_deconvolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_deconvolution "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_deconvolution.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_deconvolution NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_deconvolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_deconvolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_deconvolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_deconvolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_deconvolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_deconvolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_deconvolutiondepthwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_deconvolutiondepthwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_deconvolutiondepthwise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_deepcopy "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_deepcopy.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_deepcopy "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_deepcopy.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_deepcopy "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_deepcopy.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_deepcopy "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_deepcopy.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_deepcopy NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_dropout "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_dropout.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_dropout "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_dropout.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_dropout "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_dropout.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_dropout "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_dropout.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_dropout NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_eltwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_eltwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_eltwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_eltwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_eltwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_eltwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_eltwise "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_eltwise.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_eltwise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_elu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_elu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_elu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_elu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_elu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_elu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_elu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_elu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_elu NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_flatten "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_flatten.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_flatten "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_flatten.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_flatten "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_flatten.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_flatten "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_flatten.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_flatten NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gemm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_gemm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gemm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_gemm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gemm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_gemm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gemm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_gemm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_gemm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_groupnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_groupnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_groupnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_groupnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_groupnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_groupnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_groupnorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_groupnorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_groupnorm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hardsigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_hardsigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hardsigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_hardsigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hardsigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_hardsigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hardsigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_hardsigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_hardsigmoid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hardswish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_hardswish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hardswish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_hardswish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hardswish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_hardswish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hardswish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_hardswish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_hardswish NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_innerproduct "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_innerproduct.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_innerproduct "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_innerproduct.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_innerproduct "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_innerproduct.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_innerproduct "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_innerproduct.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_innerproduct NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_instancenorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_instancenorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_instancenorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_instancenorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_instancenorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_instancenorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_instancenorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_instancenorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_instancenorm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_interp "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_interp.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_interp "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_interp.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_interp "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_interp.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_interp "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_interp.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_interp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_layernorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_layernorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_layernorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_layernorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_layernorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_layernorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_layernorm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_layernorm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_layernorm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lrn "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_lrn.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lrn "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_lrn.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lrn "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_lrn.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lrn "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_lrn.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_lrn NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_memorydata "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_memorydata.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_memorydata "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_memorydata.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_memorydata "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_memorydata.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_memorydata "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_memorydata.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_memorydata NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_noop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_noop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_noop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_noop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_noop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_noop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_noop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_noop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_noop NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_normalize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_normalize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_normalize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_normalize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_normalize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_normalize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_normalize "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_normalize.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_normalize NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_packing "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_packing.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_packing "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_packing.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_packing "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_packing.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_packing "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_packing.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_packing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_padding "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_padding.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_padding "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_padding.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_padding "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_padding.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_padding "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_padding.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_padding NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_permute "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_permute.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_permute "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_permute.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_permute "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_permute.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_permute "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_permute.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_permute NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_pixelshuffle "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_pixelshuffle.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_pixelshuffle "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_pixelshuffle.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_pixelshuffle "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_pixelshuffle.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_pixelshuffle "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_pixelshuffle.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_pixelshuffle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_pooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_pooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_pooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_pooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_pooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_pooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_pooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_pooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_pooling NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_prelu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_prelu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_prelu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_prelu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_prelu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_prelu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_prelu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_prelu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_prelu NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_priorbox "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_priorbox.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_priorbox "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_priorbox.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_priorbox "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_priorbox.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_priorbox "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_priorbox.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_priorbox NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_roipooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_roipooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_roipooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_roipooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_roipooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_roipooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_roipooling "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_roipooling.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_roipooling NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_roialign "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_roialign.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_roialign "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_roialign.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_roialign "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_roialign.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_roialign "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_roialign.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_roialign NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_relu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_relu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_relu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_relu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_relu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_relu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_relu "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_relu.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_relu NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_reorg "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_reorg.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_reorg "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_reorg.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_reorg "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_reorg.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_reorg "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_reorg.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_reorg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_reshape "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_reshape.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_reshape "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_reshape.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_reshape "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_reshape.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_reshape "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_reshape.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_reshape NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_scale "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_scale.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_scale "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_scale.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_scale "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_scale.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_scale "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_scale.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_scale NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_shufflechannel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_shufflechannel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_shufflechannel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_shufflechannel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_shufflechannel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_shufflechannel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_shufflechannel "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_shufflechannel.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_shufflechannel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_sigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_sigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_sigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sigmoid "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_sigmoid.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_sigmoid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_slice "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_slice.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_slice "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_slice.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_slice "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_slice.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_slice "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_slice.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_slice NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_softmax "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_softmax.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_softmax "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_softmax.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_softmax "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_softmax.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_softmax "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_softmax.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_softmax NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_tanh "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_tanh.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_tanh "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_tanh.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_tanh "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_tanh.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_tanh "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_tanh.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_tanh NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_unaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_unaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_unaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_unaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_unaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_unaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_unaryop "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_unaryop.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_unaryop NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_mish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_mish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_mish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_mish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_mish NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_swish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_swish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_swish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_swish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_swish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_swish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_swish "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_swish.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_swish NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lstm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_lstm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lstm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_lstm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lstm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_lstm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lstm "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_lstm.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_lstm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_yolov3detectionoutput "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_yolov3detectionoutput.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_yolov3detectionoutput "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_yolov3detectionoutput.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_yolov3detectionoutput "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_yolov3detectionoutput.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_yolov3detectionoutput "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_yolov3detectionoutput.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_yolov3detectionoutput NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_softplus "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Debug/test_softplus.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_softplus "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/Release/test_softplus.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_softplus "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/MinSizeRel/test_softplus.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_softplus "D:/Software/CMake/bin/cmake.exe" "-DTEST_EXECUTABLE=F:/pytorch2ncnn/ncnn/build_cmakegui/tests/RelWithDebInfo/test_softplus.exe" "-P" "F:/pytorch2ncnn/ncnn/tests/../cmake/run_test.cmake")
else()
  add_test(test_softplus NOT_AVAILABLE)
endif()
